import os
import numpy as np

# ------- 用户配置区域 -------
# 你的完整文件夹路径
base_path = r'C:\Users\19807\Desktop\模型实际应用\NEB优化2-5\neb'

OutputName = 'POSCAR.vasp'  # 输出文件名
VisualAtom = 'Li'           # 迁移原子显示的名称

# 你的文件夹是 00 到 09，共 10 个文件夹。
Images = 9

# 【修改点】迁移原子在 POSCAR 中的位置
# 如果是列表中的第 6 个原子，这里填 6
mig_atom_index = 2 
# ---------------------------

def read_poscar(filepath):
    """读取 POSCAR 文件"""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()
    
    data = {
        'title': lines[0].strip(),
        'scale': float(lines[1].strip()),
        'lattice': np.array([list(map(float, lines[i].split())) for i in range(2, 5)]),
        'elements': lines[5].split(),
        'atom_counts': list(map(int, lines[6].split())),
        'coord_type': lines[7].split()[0],
        'coordinates': []
    }
    
    # 计算原子总数以读取坐标
    total_atoms = sum(data['atom_counts'])
    for i in range(8, 8 + total_atoms):
        data['coordinates'].append(list(map(float, lines[i].split())))
        
    data['coordinates'] = np.array(data['coordinates'])
    return data

# 主程序
if __name__ == "__main__":
    all_data = []
    
    print(f"正在读取路径: {base_path} ...")
    print(f"设定迁移原子为列表中的第 {mig_atom_index} 个原子...")
    
    # 1. 读取所有 POSCAR 文件 (00 到 09)
    for i in range(Images + 2):
        folder_name = f"{i:02d}" # 格式化为 00, 01...
        file_path = os.path.join(base_path, folder_name, "CONTCAR")
        
        if os.path.exists(file_path):
            data = read_poscar(file_path)
            all_data.append(data)
            print(f"成功读取: {folder_name}")
        else:
            print(f"错误: 未找到文件 {file_path}")
            exit()

    # 2. 准备输出数据
    # 选取最后一个图像 (09) 作为骨架结构
    final_data = all_data[-1]
    
    # 【逻辑自动处理】获取非迁移原子的坐标
    # 计算机索引从 0 开始，所以第 6 个原子的索引是 mig_atom_index - 1 (即 5)
    target_idx = mig_atom_index - 1
    
    # 使用 np.delete 删除指定索引的原子，保留其余作为骨架
    backbone_coords = np.delete(final_data['coordinates'], target_idx, axis=0)
    
    # 【逻辑自动处理】收集所有图像的迁移原子坐标
    migration_coords = []
    for data in all_data:
        # 提取第 6 个原子 (索引 target_idx)
        migration_coords.append(data['coordinates'][target_idx])
    
    migration_coords = np.array(migration_coords)
    
    # 合并坐标：骨架 + 所有迁移路径点
    final_coords = np.vstack((backbone_coords, migration_coords))
    
    # 3. 修改元素计数
    out_elements = final_data['elements'][:]
    out_counts = final_data['atom_counts'][:]
    
    # 【逻辑自动处理】智能判断第 6 个原子属于哪种元素
    current_count_sum = 0
    element_type_idx_to_reduce = -1
    
    for i, count in enumerate(out_counts):
        # 检查目标原子索引是否落在当前元素的范围内
        if current_count_sum <= target_idx < current_count_sum + count:
            element_type_idx_to_reduce = i
            break
        current_count_sum += count
        
    if element_type_idx_to_reduce == -1:
        print("错误：无法确定迁移原子属于哪种元素，请检查原子总数。")
        exit()
    
    # 减少对应元素的计数 (减 1)
    out_counts[element_type_idx_to_reduce] = out_counts[element_type_idx_to_reduce] - 1
    
    # 添加新的 VisualAtom (Li) 及其数量 (图像数量)
    out_elements.append(VisualAtom)
    out_counts.append(Images + 2)
    
    # 4. 写入文件
    with open(OutputName, 'w') as f:
        f.write("Generated by Python Script (Li migration)\n")
        f.write(f"{final_data['scale']:.16f}\n")
        
        # 写入晶格矢量
        for vec in final_data['lattice']:
            f.write(f"{vec[0]:20.16f} {vec[1]:20.16f} {vec[2]:20.16f}\n")
            
        # 写入元素符号
        f.write(" ".join(out_elements) + "\n")
        
        # 写入元素数量
        f.write(" ".join(map(str, out_counts)) + "\n")
        
        # 写入坐标类型
        f.write(f"{final_data['coord_type']}\n")
        
        # 写入坐标
        for coord in final_coords:
            f.write(f"  {coord[0]:20.16f}  {coord[1]:20.16f}  {coord[2]:20.16f}\n")
            
    print(f"成功生成: {OutputName}")